/* User: 1803982879 Password: mypassword */
DROP DATABASE 1803982879_dub16;

CREATE DATABASE 1803982879_dub16;

USE 1803982879_dub16;

CREATE TABLE Medlimur(
ID INT(3) PRIMARY KEY AUTO_INCREMENT NOT NULL,
nafn VARCHAR(255),
kennitala CHAR(10),
simi CHAR(7)
);

CREATE TABLE Vidburdur(
ID INT(3) PRIMARY KEY AUTO_INCREMENT NOT NULL,
heiti VARCHAR(255),
dagsetning DATE
);

CREATE TABLE Admin(
ID INT(3) PRIMARY KEY AUTO_INCREMENT NOT NULL,
medlimur_ID INT(3) NOT NULL,
FOREIGN KEY (medlimur_ID) REFERENCES Medlimur(ID)
);

CREATE TABLE Skraning(
vidburdur_id INT(3) NOT NULL,
medlimur_id INT(3) NOT NULL,
FOREIGN KEY (vidburdur_id) REFERENCES Vidburdur(ID),
FOREIGN KEY (medlimur_ID) REFERENCES Medlimur(ID)
);